"""Seed antibodies — curated India-relevant rumors with full verdicts.

These give the memory immediate "known rumor -> instant verdict" hits (our free,
self-owned alternative to the Google Fact Check API, and stronger for local
rumors that no global fact-check DB covers). `key_text` is what gets embedded;
`result` is the full verdict the engine would otherwise produce.
"""
from __future__ import annotations
from offline import GARLIC, VAN

SEED = [
    {"key_text": "Eating raw garlic cures coronavirus, doctors confirm it, no need for hospital.",
     "result": {**GARLIC, "claims": GARLIC["claims"]}, "checks": 48210, "age": "3 days ago"},
    {"key_text": "A white van is kidnapping children near the market, police are silent, forward to every parent.",
     "result": {**VAN, "claims": VAN["claims"]}, "checks": 33800, "age": "1 day ago"},
    {"key_text": "The government is giving FREE laptops to all students, register before midnight at this link.",
     "result": {
        "verdict": "false", "confidence": 94, "domain": "finance",
        "claims": ["The government is giving free laptops to all students.", "The registration link is official."],
        "sources": [
            {"org": "PIB Fact Check", "badge": "P", "url": "pib.gov.in/factcheck", "note": "No such 'free laptop for all students' scheme exists; flagged as fake."},
            {"org": "Domain check", "badge": "D", "url": "", "note": "The link resolves to a known credential-phishing host, not a government domain."},
        ],
        "meaningEn": "This is a scam. There is no such government scheme, and the link is built to steal your details. Do not enter anything or forward it.",
        "meaningHi": "यह एक धोखा है। ऐसी कोई सरकारी योजना नहीं है, और यह लिंक आपकी जानकारी चुराने के लिए बना है। कुछ न भरें और न आगे भेजें।",
        "counterEn": "Heads up — I checked this. There's no government free-laptop scheme; the link is a phishing scam meant to steal your details. Please don't register or forward it.",
        "counterHi": "ध्यान दें — मैंने जाँच की। सरकार की कोई फ्री लैपटॉप योजना नहीं है; यह लिंक आपकी जानकारी चुराने वाला धोखा है। कृपया रजिस्टर न करें और न भेजें।",
        "weighNote": "No such scheme exists on official sources, and the link is a known phishing domain — both point clearly to false.",
        "escalate": False,
     }, "checks": 91300, "age": "2 hours ago"},
    {"key_text": "RBI will withdraw all 500 rupee notes on December 31, deposit yours before the deadline or lose the money.",
     "result": {
        "verdict": "false", "confidence": 89, "domain": "finance",
        "claims": ["RBI is withdrawing all ₹500 notes on Dec 31.", "Money is lost if not deposited by then."],
        "sources": [
            {"org": "RBI", "badge": "R", "url": "rbi.org.in", "note": "No such notice exists in RBI's press releases; ₹500 notes remain legal tender."},
            {"org": "Reuters Fact Check", "badge": "R", "url": "reuters.com/fact-check", "note": "An identical earlier claim was rated false."},
        ],
        "meaningEn": "This is false. The RBI has issued no such order — your ₹500 notes are still valid. It's a recurring rumor that scares people into panic.",
        "meaningHi": "यह झूठ है। RBI ने ऐसा कोई आदेश नहीं दिया — आपके ₹500 के नोट अब भी वैध हैं। यह बार-बार फैलने वाली अफवाह है जो लोगों को डराती है।",
        "counterEn": "I checked — the RBI has issued no such order. ₹500 notes are still valid. This same rumor has spread before and was found false. No need to rush to the bank.",
        "counterHi": "मैंने जाँचा — RBI ने ऐसा कोई आदेश नहीं दिया। ₹500 के नोट अब भी वैध हैं। यही अफवाह पहले भी झूठी निकली थी। बैंक भागने की ज़रूरत नहीं।",
        "weighNote": "No RBI notice exists and the same claim was debunked before — clearly false, though it causes real financial panic.",
        "escalate": False,
     }, "checks": 27600, "age": "5 hours ago"},
    {"key_text": "Drinking warm water every 15 minutes flushes the coronavirus from your throat so stomach acid kills it.",
     "result": {
        "verdict": "misleading", "confidence": 86, "domain": "health",
        "claims": ["Warm water flushes the virus out of the throat.", "Stomach acid then kills the virus."],
        "sources": [
            {"org": "WHO", "badge": "W", "url": "who.int/myth-busters", "note": "There is no evidence that drinking water flushes out or kills the virus."},
            {"org": "ICMR (India)", "badge": "I", "url": "icmr.gov.in", "note": "Not a recognised preventive measure for COVID-19."},
        ],
        "meaningEn": "Staying hydrated is good, but warm water does NOT flush out or kill the coronavirus. Relying on it instead of real precautions is risky.",
        "meaningHi": "पानी पीना अच्छा है, पर गर्म पानी कोरोना को न बहाता है न मारता है। असली सावधानियों की जगह इस पर भरोसा करना खतरनाक है।",
        "counterEn": "I checked this. Drinking warm water is fine for hydration, but it does NOT remove or kill the virus — the WHO and ICMR confirm that. Please don't rely on it instead of real precautions.",
        "counterHi": "मैंने जाँचा। गर्म पानी पीना ठीक है पर यह वायरस को न हटाता है न मारता है — WHO और ICMR यही कहते हैं। कृपया असली सावधानियों की जगह इस पर भरोसा न करें।",
        "weighNote": "Hydration has a grain of truth, but the 'flushes out the virus' mechanism is invented — so misleading, not outright false.",
        "escalate": True,
     }, "checks": 19400, "age": "1 day ago"},
    {"key_text": "The new currency note contains a hidden GPS or nano tracking chip.",
     "result": {
        "verdict": "false", "confidence": 91, "domain": "general",
        "claims": ["New currency notes contain a hidden GPS/nano tracking chip."],
        "sources": [
            {"org": "RBI", "badge": "R", "url": "rbi.org.in", "note": "Notes carry standard security features (watermark, thread) — no chip."},
            {"org": "PIB Fact Check", "badge": "P", "url": "pib.gov.in/factcheck", "note": "Rated the 'tracking chip' claim as false."},
        ],
        "meaningEn": "This is false. Currency notes have normal security features like watermarks and threads, but no GPS or tracking chip — that isn't physically possible in paper notes.",
        "meaningHi": "यह झूठ है। नोटों में वॉटरमार्क और धागे जैसी सामान्य सुरक्षा होती है, पर कोई GPS या ट्रैकिंग चिप नहीं — कागज़ के नोट में यह संभव ही नहीं।",
        "counterEn": "I checked — there's no tracking chip in any currency note. They only have normal security features like watermarks. The RBI and fact-checkers have confirmed this is false.",
        "counterHi": "मैंने जाँचा — किसी नोट में ट्रैकिंग चिप नहीं है। उनमें सिर्फ़ वॉटरमार्क जैसी सामान्य सुरक्षा होती है। RBI और फैक्ट-चेकर इसे झूठ बता चुके हैं।",
        "weighNote": "Contradicted by RBI and physically implausible — clearly false.",
        "escalate": False,
     }, "checks": 15400, "age": "2 days ago"},
    {"key_text": "The 2000 rupee note is now banned and worthless, your notes are no longer valid money.",
     "result": {
        "verdict": "false", "confidence": 88, "domain": "finance",
        "claims": ["₹2000 notes are banned and worthless.", "They are no longer valid money."],
        "sources": [
            {"org": "RBI", "badge": "R", "url": "rbi.org.in", "note": "₹2000 notes were withdrawn from circulation in 2023 but REMAIN legal tender; they can still be deposited/exchanged."},
            {"org": "PIB Fact Check", "badge": "P", "url": "pib.gov.in/factcheck", "note": "Claims that the notes are 'worthless' are false."},
        ],
        "meaningEn": "This is false. The RBI stopped printing ₹2000 notes, but they are still legal money you can deposit or exchange at a bank. They are not worthless.",
        "meaningHi": "यह झूठ है। RBI ने ₹2000 के नोट छापना बंद किया, पर ये अब भी वैध पैसा हैं जिन्हें बैंक में जमा या बदला जा सकता है। ये बेकार नहीं हैं।",
        "counterEn": "I checked — ₹2000 notes are still legal tender. The RBI only stopped printing them; you can still deposit or exchange them at a bank. They are not worthless.",
        "counterHi": "मैंने जाँचा — ₹2000 के नोट अब भी वैध हैं। RBI ने सिर्फ़ छापना बंद किया है; आप उन्हें बैंक में जमा या बदल सकते हैं। ये बेकार नहीं हैं।",
        "weighNote": "Withdrawn from circulation is true, but 'banned and worthless' is false — they remain legal tender.",
        "escalate": False,
     }, "checks": 22400, "age": "6 hours ago"},
    {"key_text": "If you get a missed call from an international number starting with +92, your bank account will be hacked instantly, never call back.",
     "result": {
        "verdict": "false", "confidence": 90, "domain": "finance",
        "claims": ["A missed call from a +92 number can hack your bank account.", "Calling back drains your account."],
        "sources": [
            {"org": "PIB Fact Check", "badge": "P", "url": "pib.gov.in/factcheck", "note": "A missed call alone cannot access or empty a bank account; rated false."},
            {"org": "BOOM Live", "badge": "B", "url": "boomlive.in", "note": "Recurring viral hoax; a phone call cannot transfer money or steal OTPs by itself."},
        ],
        "meaningEn": "This is false. A missed or answered call cannot hack your bank account — money is only lost if YOU share an OTP, PIN, or install an app a scammer asks for. The call itself is harmless.",
        "meaningHi": "यह झूठ है। मिस्ड या उठाई गई कॉल आपका बैंक खाता हैक नहीं कर सकती — पैसा तभी जाता है जब आप खुद OTP, PIN बताएँ या ठग का बताया ऐप डालें। कॉल खुद नुकसान नहीं करती।",
        "counterEn": "I checked — a missed call can't hack your account. You only lose money if you share an OTP/PIN or install something a scammer tells you to. The number itself is harmless; just don't share codes.",
        "counterHi": "मैंने जाँचा — मिस्ड कॉल खाता हैक नहीं कर सकती। पैसा तभी जाता है जब आप OTP/PIN बताएँ या ठग का कहा कुछ इंस्टॉल करें। नंबर खुद नुकसान नहीं करता; बस कोड किसी को न बताएँ।",
        "weighNote": "The technical mechanism is impossible and fact-checkers rate it false, though the underlying OTP-scam warning is real.",
        "escalate": False,
     }, "checks": 41200, "age": "4 hours ago"},
    {"key_text": "UNESCO has officially declared Jana Gana Mana the best national anthem in the world.",
     "result": {
        "verdict": "false", "confidence": 92, "domain": "general",
        "claims": ["UNESCO declared 'Jana Gana Mana' the best national anthem in the world."],
        "sources": [
            {"org": "UNESCO", "badge": "U", "url": "unesco.org", "note": "UNESCO does not rate or rank national anthems and has issued no such declaration."},
            {"org": "Alt News", "badge": "A", "url": "altnews.in", "note": "A recurring hoax since 2008; UNESCO confirmed it made no such statement."},
        ],
        "meaningEn": "This is false. UNESCO does not rank national anthems and never made this statement. It's a feel-good hoax that has circulated for years.",
        "meaningHi": "यह झूठ है। UNESCO राष्ट्रगानों की रैंकिंग नहीं करता और उसने ऐसा कभी नहीं कहा। यह सालों से फैलने वाली एक झूठी 'गर्व' अफवाह है।",
        "counterEn": "I checked — UNESCO doesn't rank national anthems and never said this. It's a hoax that's been forwarded for years. Nice sentiment, but not true.",
        "counterHi": "मैंने जाँचा — UNESCO राष्ट्रगानों की रैंकिंग नहीं करता और उसने ऐसा कभी नहीं कहा। यह सालों से फैलने वाली अफवाह है। भावना अच्छी है, पर सच नहीं।",
        "weighNote": "UNESCO has no such programme and explicitly denied it — clearly false.",
        "escalate": False,
     }, "checks": 38900, "age": "1 day ago"},
    {"key_text": "Keeping a cut onion in the room overnight absorbs all the germs and viruses and protects your family from infection.",
     "result": {
        "verdict": "false", "confidence": 87, "domain": "health",
        "claims": ["A cut onion in a room absorbs germs and viruses.", "It protects the family from infection."],
        "sources": [
            {"org": "WHO", "badge": "W", "url": "who.int", "note": "No evidence that onions absorb or attract viruses/bacteria from the air."},
            {"org": "Snopes", "badge": "S", "url": "snopes.com", "note": "Long-debunked folk myth; onions do not draw in or neutralise germs."},
        ],
        "meaningEn": "This is false. A cut onion does not absorb germs or viruses from the air — there's no science behind it. It can't protect anyone from infection.",
        "meaningHi": "यह झूठ है। कटा प्याज़ हवा से कीटाणु या वायरस नहीं सोखता — इसका कोई वैज्ञानिक आधार नहीं। यह किसी को संक्रमण से नहीं बचा सकता।",
        "counterEn": "I checked — a cut onion doesn't absorb germs or viruses from the air. It's an old myth with no science behind it. Real protection is hygiene, ventilation, and vaccines.",
        "counterHi": "मैंने जाँचा — कटा प्याज़ हवा से कीटाणु नहीं सोखता। यह बिना विज्ञान वाली पुरानी अफवाह है। असली बचाव है साफ़-सफ़ाई, हवादार कमरा और टीका।",
        "weighNote": "No mechanism and explicitly debunked by health bodies — clearly false.",
        "escalate": False,
     }, "checks": 12800, "age": "3 days ago"},
    {"key_text": "The COVID-19 vaccine causes infertility and changes your DNA, the government is hiding it.",
     "result": {
        "verdict": "false", "confidence": 93, "domain": "health",
        "claims": ["COVID-19 vaccines cause infertility.", "The vaccine changes your DNA.", "The government is hiding this."],
        "sources": [
            {"org": "WHO", "badge": "W", "url": "who.int", "note": "No evidence COVID-19 vaccines affect fertility; mRNA does not enter or alter DNA."},
            {"org": "ICMR (India)", "badge": "I", "url": "icmr.gov.in", "note": "Vaccines do not cause infertility; extensively studied and refuted."},
            {"org": "AIIMS", "badge": "A", "url": "aiims.edu", "note": "Doctors confirm no link between the vaccine and infertility or DNA change."},
        ],
        "meaningEn": "This is false and dangerous. COVID-19 vaccines do not cause infertility and cannot change your DNA — this has been studied widely. Believing it can stop people from getting protected.",
        "meaningHi": "यह झूठ और खतरनाक है। कोविड टीके न बाँझपन करते हैं न DNA बदलते हैं — इस पर बहुत शोध हो चुका है। इस पर भरोसा लोगों को बचाव से रोक सकता है।",
        "counterEn": "I checked — COVID vaccines do NOT cause infertility and can't change your DNA. This has been studied in millions of people. The WHO, ICMR and AIIMS all confirm it. Please don't let this scare anyone out of getting protected.",
        "counterHi": "मैंने जाँचा — कोविड टीके न बाँझपन करते हैं न DNA बदलते हैं। लाखों लोगों पर अध्ययन हुआ है। WHO, ICMR और AIIMS सब इसकी पुष्टि करते हैं। कृपया इस डर से किसी को टीके से न रोकें।",
        "weighNote": "Contradicted by every major health authority; the DNA-change mechanism is biologically impossible — clearly false and high-harm.",
        "escalate": True,
     }, "checks": 56700, "age": "8 hours ago"},
    {"key_text": "Gargling with warm salt water cures COVID-19 and clears the virus before it reaches your lungs.",
     "result": {
        "verdict": "misleading", "confidence": 84, "domain": "health",
        "claims": ["Salt-water gargling cures COVID-19.", "It clears the virus before it reaches the lungs."],
        "sources": [
            {"org": "WHO", "badge": "W", "url": "who.int/myth-busters", "note": "Gargling salt water does not cure or prevent COVID-19, though it may soothe a sore throat."},
            {"org": "ICMR (India)", "badge": "I", "url": "icmr.gov.in", "note": "Not a treatment or preventive for COVID-19."},
        ],
        "meaningEn": "Salt-water gargling can soothe a sore throat, but it does NOT cure COVID-19 or stop the virus reaching your lungs. Treating it as a cure is risky.",
        "meaningHi": "नमक के पानी से गरारे गले को आराम दे सकते हैं, पर यह कोविड को न ठीक करता है न वायरस को फेफड़ों तक जाने से रोकता है। इसे इलाज समझना खतरनाक है।",
        "counterEn": "I checked — gargling salt water is fine for a sore throat, but it does NOT cure COVID or stop the virus reaching your lungs. The WHO confirms this. Please see a doctor for real symptoms.",
        "counterHi": "मैंने जाँचा — नमक के पानी के गरारे गले के लिए ठीक हैं, पर ये कोविड को न ठीक करते हैं न वायरस रोकते हैं। WHO यही कहता है। असली लक्षणों के लिए डॉक्टर को दिखाएँ।",
        "weighNote": "Gargling genuinely soothes a throat (the grain of truth), but the 'cure / stops it reaching lungs' claim is invented — misleading, not outright false.",
        "escalate": True,
     }, "checks": 17300, "age": "2 days ago"},
]
